---
- name: Install default packages
  package:
    name:
      - python3
      - python3-pip
      - python3-kubernetes
    state: present
  when: inventory_hostname == master_node

- name: Copy K3s service file (First master for cluster-init)
  register: k3s_service
  template:
    src: "clusterinit_k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0644
  when: inventory_hostname == master_node

- name: Enable and check K3s service
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes
  when: inventory_hostname == master_node

- name: Wait for node-token
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token
  when: inventory_hostname == master_node

- name: Register node-token file access mode
  stat:
    path: /var/lib/rancher/k3s/server
  register: p
  when: inventory_hostname == master_node

- name: Change file access node-token
  file:
    path: /var/lib/rancher/k3s/server
    mode: "g+rx,o+rx"
  when: inventory_hostname == master_node

- name: Read node-token from master
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token
  when: inventory_hostname == master_node

- name: Store Master node-token
  set_fact:
    token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"
  when: inventory_hostname == master_node

- name: Wait for API to get available
  ansible.builtin.uri:
    url: https://{{ master_ip }}:6443
    validate_certs: false
    status_code: 
      - 200
      - 401
  register: result
  until: "result.status == 401"
  retries: 10
  delay: 10

- name: Copy K3s service file (Join other masters)
  register: k3s_service
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0644
  when: inventory_hostname != master_node

- name: Enable and check K3s service
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes
  when: inventory_hostname != master_node

- name: Restore node-token file access
  file:
    path: /var/lib/rancher/k3s/server
    mode: "{{ p.stat.mode }}"
  when: inventory_hostname == master_node

- name: Create directory .kube
  file:
    path: ~{{ lookup('env', 'USER') }}/.kube
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
    mode: "u=rwx,g=rx,o="
  when: inventory_hostname == master_node

- name: Copy config file to user home directory
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~{{ lookup('env', 'USER') }}/.kube/config
    remote_src: yes
    owner: "{{ lookup('env', 'USER') }}"
    mode: "u=rw,g=,o="
  when: inventory_hostname == master_node

- name: Replace https://localhost:6443 by https://master-ip:6443
  command: >-
    k3s kubectl config set-cluster default
      --server=https://{{ master_ip }}:6443
      --kubeconfig ~{{ lookup('env', 'USER') }}/.kube/config
  changed_when: true

- name: Create kubectl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Create crictl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link