---
- name: Deploy MetalLB to the cluster
  kubernetes.core.k8s:
    state: present
    src: files/metallb-native.yaml

- name: Pause for 1 minute to setup metallb 
  ansible.builtin.pause:
    minutes: 1

- name: Create IPAdressPool for MetalLB
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: default-ip-pool
        namespace: metallb-system
      spec:
        addresses: "{{ metallb_ip_address_pool }}"

- name: Create L2Advertisement for MetalLB
  kubernetes.core.k8s:
    state: present
    definition:  
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: metallb-pool
        namespace: metallb-system
      spec:
        ipAddressPools:
        - default-ip-pool
