---
- name: Add cert-manager helm repository
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: Deploy cert-manager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    create_namespace: true
    release_namespace: cert-manager
    set_values:
      - value: "crds.enabled=true"
